version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fornecedores-app
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        depends_on:
            - mysql
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=fornecedores_db
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
            - BRASILAPI_BASE_URL=https://brasilapi.com.br/api
            - BRASILAPI_TIMEOUT=15
            - BRASILAPI_VERIFY_SSL=false
            - BRASILAPI_RETRY_ATTEMPTS=3
            - BRASILAPI_USER_AGENT=Laravel/10.0 BrasilAPI Client
        networks:
            - fornecedores-network

    mysql:
        image: mysql:8.0
        container_name: fornecedores-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: fornecedores_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - fornecedores-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: fornecedores-phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: laravel
            PMA_PASSWORD: laravel
        depends_on:
            - mysql
        networks:
            - fornecedores-network

volumes:
    mysql_data:
        driver: local

networks:
    fornecedores-network:
        driver: bridge
